name: CI Pipeline with Aqua Scanner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t caddy:2.4.0 .

      # Step 3: Log in to Docker registry securely
      - name: Log in to Docker registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login aquapartners.azurecr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 4: Run Aqua Container Scanner
      - name: Aqua Container Scanner
        run: |
         docker run -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:latest-saas scan -H https://77f96608de.cloud.aquasec.com -A 4ee93d8acd2a35da266c413af5d79d8dc1df14ec4837d150fb9a5817622ea798 --local caddy:2.4.0
